eureka:

  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
    registerWithEureka: true
    fetch-registry: true

server:
  port: 8080

spring:

  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST

      routes:
        - id: doctor_service
          uri: http://localhost:8081
          predicates:
            - Path=/doctor-api/**
          filters:
            - AuthenticationFilter
            
        - id: patient_service
          uri: http://localhost:8082
          predicates:
            - Path=/patient-api/**
          filters:
            - AuthenticationFilter
        
        - id: appointment_service
          uri: http://localhost:8083
          predicates:
            - Path=/appointment-api/**
          filters:
            - AuthenticationFilter
            
        - id: pharmacy_service
          uri: http://localhost:8085
          predicates:
            - Path=/pharmacy-api/**
          filters:
            - AuthenticationFilter
            
        - id: disease-prediction-service
          uri: http://localhost:8980
          predicates:
            - Path=/prediction-api/**
          filters:
            - AuthenticationFilter        

        - id: authentication-service
          uri: http://localhost:8087
          predicates:
            - Path=/auth/**
      
            
            
